apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "myrdp.fullname" . }}
  labels:
    {{- include "myrdp.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "myrdp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "myrdp.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "myrdp.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: rdp
              containerPort: 3389
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: rdp
          readinessProbe:
            tcpSocket:
              port: rdp
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{ range $path, $bytes := .Files.Glob  "xfce/**" }}
            {{ $name := base $path }}
              - name: cm-multi-file-volume
                mountPath: {{ printf "/usr/share/backgrounds/xfce/%s"  $name | indent 2 }}
                subPath: {{- sha256sum (printf "xfce/%s" $name ) | indent 2 }}
            {{ end }}    
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
            - name: cm-multi-file-volume
              configMap:
                name: cm-multi-file-rdp